name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.2
        with:
          pixi-version: v0.28.0

      - name: Install (regrid env)
        run: |
          pixi install -e regrid

      - name: Lint
        run: |
          pixi run -e regrid lint
          pixi run -e regrid format-check

      - name: Run tests
        run: |
          pixi run -e regrid test
